-- reincarnation2 blog · Supabase schema
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'reincarnation2',
  email text,
  qq text default '1706638282',
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  slug text not null unique,
  excerpt text not null default '',
  content text not null default '',
  content_html text,
  content_format text not null default 'plain',
  cover_url text,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  featured boolean not null default false,
  read_time_minutes integer not null default 5 check (read_time_minutes > 0),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  guest_name text,
  guest_email text,
  body text not null check (char_length(body) between 1 and 2000),
  body_html text,
  body_plain text,
  attachments jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) on delete set null,
  guest_name text not null,
  guest_email text,
  body text not null check (char_length(body) between 1 and 1000),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete set null,
  file_name text not null,
  public_url text not null,
  storage_path text,
  alt_text text,
  purpose text,
  created_at timestamptz not null default now()
);

create index if not exists posts_status_published_idx on public.posts(status, published_at desc);
create index if not exists posts_category_idx on public.posts(category_id);
create index if not exists comments_post_status_idx on public.comments(post_id, status, created_at desc);

insert into public.categories (name, slug, description) values
  ('随笔', 'essay', '记录日常和未归类的念头'),
  ('技术', 'tech', '代码、工具和重构记录'),
  ('生活', 'life', '生活观察与个人片段'),
  ('方法', 'method', '把复杂问题写下来的方法')
on conflict (slug) do nothing;

-- Create/update a profile after Supabase Auth registration.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', 'reincarnation2'), new.email)
  on conflict (id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.guestbook_messages enable row level security;
alter table public.media enable row level security;

drop policy if exists "published posts are public" on public.posts;
drop policy if exists "admins manage posts" on public.posts;
drop policy if exists "demo can read posts" on public.posts;
drop policy if exists "demo can insert posts" on public.posts;
drop policy if exists "demo can update posts" on public.posts;
drop policy if exists "demo can delete posts" on public.posts;
create policy "demo can read posts" on public.posts for select using (true);
create policy "demo can insert posts" on public.posts for insert with check (true);
create policy "demo can update posts" on public.posts for update using (true) with check (true);
create policy "demo can delete posts" on public.posts for delete using (true);

drop policy if exists "categories are public" on public.categories;
create policy "categories are public" on public.categories for select using (true);
drop policy if exists "admins manage categories" on public.categories;
create policy "admins manage categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "approved comments are public" on public.comments;
drop policy if exists "guests can submit comments" on public.comments;
drop policy if exists "admins moderate comments" on public.comments;
drop policy if exists "demo can read comments" on public.comments;
drop policy if exists "demo can write comments" on public.comments;
drop policy if exists "demo can update comments" on public.comments;
create policy "demo can read comments" on public.comments for select using (true);
create policy "demo can write comments" on public.comments for insert with check (true);
create policy "demo can update comments" on public.comments for update using (true) with check (true);

drop policy if exists "approved guestbook is public" on public.guestbook_messages;
drop policy if exists "guests can sign guestbook" on public.guestbook_messages;
drop policy if exists "admins moderate guestbook" on public.guestbook_messages;
drop policy if exists "demo can read guestbook" on public.guestbook_messages;
drop policy if exists "demo can write guestbook" on public.guestbook_messages;
drop policy if exists "demo can update guestbook" on public.guestbook_messages;
drop policy if exists "demo can delete guestbook" on public.guestbook_messages;
create policy "demo can read guestbook" on public.guestbook_messages for select using (true);
create policy "demo can write guestbook" on public.guestbook_messages for insert with check (true);
create policy "demo can update guestbook" on public.guestbook_messages for update using (true) with check (true);
create policy "demo can delete guestbook" on public.guestbook_messages for delete using (true);

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());

drop policy if exists "admins manage media" on public.media;
create policy "admins manage media" on public.media for all using (public.is_admin()) with check (public.is_admin());

-- After registering your account, promote it once:
-- update public.profiles set role = 'admin' where email = 'reincarnation2@qq.com';

insert into storage.buckets (id, name, public) values ('blog-media', 'blog-media', true)
on conflict (id) do update set public = true;

 drop policy if exists "public can view blog media" on storage.objects;
 create policy "public can view blog media" on storage.objects for select using (bucket_id = 'blog-media');
 drop policy if exists "admins upload blog media" on storage.objects;
 create policy "admins upload blog media" on storage.objects for insert with check (bucket_id = 'blog-media' and public.is_admin());
 drop policy if exists "admins delete blog media" on storage.objects;
 create policy "admins delete blog media" on storage.objects for delete using (bucket_id = 'blog-media' and public.is_admin());
 drop policy if exists "demo can upload rich media" on storage.objects;
 create policy "demo can upload rich media" on storage.objects for insert with check (bucket_id = 'blog-media' and (name like 'comments/%' or name like 'posts/%'));

-- Seed the current five local demo posts after Auth is configured if desired.
-- The app will also keep its local seed data until Supabase is connected.

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles for each row execute procedure public.touch_updated_at();
drop trigger if exists posts_touch_updated_at on public.posts;
create trigger posts_touch_updated_at before update on public.posts for each row execute procedure public.touch_updated_at();

-- Protect the service-role secret: never put it in VITE_ variables or browser code.
-- It bypasses RLS and belongs only in the server environment.
