import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
export const sb=createClient('https://rxjgnaldzryzkyoxgrle.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4amduYWxkenJ5emt5b3hncmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNDYzNzUsImV4cCI6MjEwNTYyMjM3NX0.9YFteJnn1SH4byYmw_EvHWMT4fV8cedz6xmgHUXcJMs');
export const $=s=>document.querySelector(s);export const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
export const date=s=>s?new Date(s).toLocaleDateString('zh-CN',{year:'numeric',month:'short',day:'numeric'}):'未发布';
export const category=p=>p.category?.name||p.category||'随笔';
export const reading=p=>p.read_time_minutes||Math.max(1,Math.ceil((p.content||'').length/220));
export const plain=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
export const safeHTML=(html,text)=>html||`<p>${esc(text||'').replace(/\n/g,'<br>')}</p>`;
export function card(p){return `<article class="item"><a href="post.html?slug=${encodeURIComponent(p.slug)}">${p.cover_url?`<img class="item-media" loading="lazy" src="${esc(p.cover_url)}" alt="${esc(p.title)}">`:'<div class="item-media" aria-hidden="true"></div>'}</a><div><div class="meta"><span class="tag">${esc(category(p))}</span><span>${date(p.published_at||p.created_at)}</span><span>${reading(p)} min</span></div><h2><a href="post.html?slug=${encodeURIComponent(p.slug)}">${esc(p.title)}</a></h2><p>${esc(p.excerpt||plain(p.content).slice(0,150)||'打开文章阅读正文。')}</p></div></article>`}
export async function published(){const r=await sb.from('posts').select('id,title,slug,excerpt,content,content_html,cover_url,status,featured,read_time_minutes,published_at,created_at,updated_at,category:categories(name,slug)').eq('status','published').order('published_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
export function shell(active='文章'){return `<div class="shell"><header class="topbar"><a class="brand" href="index.html"><i></i>reincarnation.log</a><nav class="nav"><a class="${active==='首页'?'active':''}" href="index.html">首页</a><a class="${active==='文章'?'active':''}" href="index.html#archive">文章</a><a class="${active==='主题'?'active':''}" href="topics.html">主题</a><a class="${active==='归档'?'active':''}" href="archive.html">归档</a><a class="${active==='关于'?'active':''}" href="about.html">关于</a></nav></header>`}
export function footer(){return `<footer class="footer"><span>© 2026 reincarnation.log · online archive</span><span><a href="guestbook.html">留言板</a> · <a href="friends.html">友链</a> · <a href="feed.xml">RSS</a> · <a href="admin.html">管理</a></span></footer></div>`}
export function bindLightbox(){document.querySelectorAll('.post-body img,.post-cover').forEach(img=>img.onclick=()=>{$('#lightbox img').src=img.src;$('#lightbox').classList.add('open')});$('#lightbox')?.addEventListener('click',e=>{if(e.target.id==='lightbox'||e.target.closest('button'))$('#lightbox').classList.remove('open')});document.addEventListener('keydown',e=>e.key==='Escape'&&$('#lightbox')?.classList.remove('open'))}
